TICKET_WIDTH_MM = 80
TICKET_WIDTH_PX = 384
MARGIN_PX = 16
FONT_FAMILY = "Courier New"
FONT_SIZE_SMALL = 8
FONT_SIZE_NORMAL = 10
FONT_SIZE_MEDIUM = 12
FONT_SIZE_LARGE = 14
FONT_SIZE_XLARGE = 16

LINE_PADDING = 5

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

CHARS_PER_LINE = 55
COL_CANT = 5
COL_DESC = 37
COL_TOTAL = 11
COL_GAP = 1

SECTION_GAP = 4

ASSETS_DIR = "assets"
OUTPUT_DIR = "output"
